name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the front end Docker image
      run: docker build . --file ./CICD/frontend/Dockerfile --tag latest:$(date +%s)
    
    - name: Build the Backend Docker image
      run: docker build . --file ./CICD/backend/Dockerfile --tag my-image-name:$(date +%s)

